# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ulk < Formula
  desc "ulk — AI-assisted development toolkit (85 agents for Claude Code)"
  homepage "https://ulk.regrets.app"
  version "5.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/izo/Ulk/releases/download/v5.0.1/ulk_darwin_amd64.tar.gz"
      sha256 "86c65c6720cc3ffd39ddec0f3577bca7743869e588149f1e334bfe3c1e66ad8a"

      define_method(:install) do
        bin.install "ulk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/izo/Ulk/releases/download/v5.0.1/ulk_darwin_arm64.tar.gz"
      sha256 "614f9d5730eb87a17a07fb04dbf4743eb43db294a662a99392b86cfb639de9ca"

      define_method(:install) do
        bin.install "ulk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/izo/Ulk/releases/download/v5.0.1/ulk_linux_amd64.tar.gz"
      sha256 "70ca6aeff0a30bdfcf3dbd0a4978e1a4ef2b9d07cc6784e047bd9cccfdd8db81"
      define_method(:install) do
        bin.install "ulk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/izo/Ulk/releases/download/v5.0.1/ulk_linux_arm64.tar.gz"
      sha256 "cdf4f7d7718c11537443860476d8157ca74df1c2c8809c4175ddb9a472029b8c"
      define_method(:install) do
        bin.install "ulk"
      end
    end
  end

  test do
    system "#{bin}/ulk", "--version"
  end
end
