# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ulk < Formula
  desc "ulk — AI-assisted development toolkit (85 agents for Claude Code)"
  homepage "https://ulk.regrets.app"
  version "5.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/izo/Ulk/releases/download/v5.1.1/ulk_darwin_amd64.tar.gz"
      sha256 "0665cfb9564e1d77670d2b4a2d42f37e863f919f7bd32129d51efbcf180fd3f4"

      define_method(:install) do
        bin.install "ulk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/izo/Ulk/releases/download/v5.1.1/ulk_darwin_arm64.tar.gz"
      sha256 "40a259466b6cce1ad71054a6615dcaaee3a9313380ae55b53dc0a93ea07ee1ca"

      define_method(:install) do
        bin.install "ulk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/izo/Ulk/releases/download/v5.1.1/ulk_linux_amd64.tar.gz"
      sha256 "4a078a0226c37cb986fb0badbe39fe16487f2f0571a5fffcad7c1d1f131b6cf1"
      define_method(:install) do
        bin.install "ulk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/izo/Ulk/releases/download/v5.1.1/ulk_linux_arm64.tar.gz"
      sha256 "3c324d4e9d9707e96c72082849bb150a20753f3e6843924851248ef30fcbd183"
      define_method(:install) do
        bin.install "ulk"
      end
    end
  end

  test do
    system "#{bin}/ulk", "--version"
  end
end
